version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    ports:
      - '80:80' # The HTTP port
      - '443:443' # The HTTPS port
      - '8080:8080' # The Web UI (enabled by --api)
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    networks:
      - default
      - traefik-net
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    networks:
      - default
      - traefik-net
    deploy:
      labels:
        - traefik.port=80
        - traefik.docker.network=traefik-net
        - traefik.frontend.rule=Host:whoami.swarmon.vadee.xyz

  api:
    image: simonvadee/swarmon-api:latest
    networks:
      - default
      - traefik-net
    deploy:
      labels:
        - traefik.port=8080
        - traefik.docker.network=traefik-net
        - traefik.frontend.rule=Host:api.swarmon.vadee.xyz

networks:
  traefik-net:
    external: true
