debug=true
defaultEntryPoints = ["http", "https"]


[entryPoints]

  [entryPoints.dashboard]
    address = ":5000"
    [entryPoints.dashboard.auth.digest]
        users = ["admin:traefik:a7f9d8497b8ec887429be5792b070d87"]

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
        entryPoint = "https"

  [entryPoints.https]
     address = ":443"
    [entryPoints.https.tls]

[api]
    entryPoint = "dashboard"

[acme]
    email = "simon.vadee@gmail.com"
    storage = "acme.json"
    entryPoint = "https"
    acmeLogging = true
    [acme.dnsChallenge]
        provider = "digitalocean" # DNS Provider name (cloudflare, OVH, gandi...)
        delayBeforeCheck = 30

    [[acme.domains]]
        main = "vadee.xyz"
        sans = ["api.swarmon.vadee.xyz", "whoami.swarmon.vadee.xyz", "db.swarmon.vadee.xyz", "db-ui.swarmon.vadee.xyz"]
    [[acme.domains]]
        main = "*.vadee.xyz"

[docker]
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = true
    network = "traefik-net"