debug=true
defaultEntryPoints = ["http", "https"]

[api]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
        entryPoint = "https"

  [entryPoints.https]
     address = ":443"
    [entryPoints.https.tls]

[acme]
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    email = "simon.vadee@gmail.com"
    storage = "acme.json"
    entryPoint = "https"
    acmeLogging = true
    [acme.dnsChallenge]
        provider = "cloudflare" # DNS Provider name (cloudflare, OVH, gandi...)
        delayBeforeCheck = 0

    [[acme.domains]]
        main = "vadee.xyz"
    [[acme.domains]]
        main = "*.vadee.xyz"

[docker]
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = true